name: Build and Deploy to GCS Staging

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCS_PROJECT }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  NEXT_PUBLIC_GOOGLE_MAP_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAP_API_KEY }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: |-
          yarn install
          yarn build-storybook
      - name: Deploy
        run: |-
          gsutil -m rsync -R dist/storybook gs://$GCS_BUCKET
